export const NOBODY_QUALITY_CHECKLIST = [
  "The image unmistakably belongs to the I AM NOBODY visual universe.",
  "There is exactly one anonymous adult human figure.",
  "The figure is standing, front-facing, centred, calm, balanced, and composed.",
  "The crop is approximately upper knees or mid-thigh to the top of the helmet.",
  "The body distance, shoulder width, head scale, and visual presence are consistent with the canonical cover.",
  "The exact canonical helmet from the original book cover is present at the fixed approved position and scale.",
  "The canonical helmet is naturally connected to the generated collar, neck, and shoulders without a visible seam, halo, duplicate edge, second visor, exposed head, or protruding alternative helmet.",
  "The visor is the same reflective iridescent visor from the canonical cover, with its restrained blue, green, violet, and golden tones unchanged.",
  "No eyes, mouth, face, beard, hair, skin, or recognisable facial feature is visible.",
  "The mask does not resemble a biker, astronaut, robot, monster, superhero, or Daft Punk helmet.",
  "The exact fixed canonical background is present, with no altered colour, texture, environment, scenery, object, or added background element.",
  "The lighting direction is coherent across helmet, collar, shoulders, clothing, and body, with believable soft contact shadows and no pasted-on appearance.",
  "The body anatomy, shoulders, arms, hands, fingers, clothing construction, and proportions are physically plausible and free of generative defects.",
  "The outfit communicates the archetype without becoming a costume, uniform caricature, or stereotype.",
  "There are no props, or only one approved restrained symbolic prop without readable or pseudo-readable text.",
  "There is no literal workplace, narrative scene, crowd, action pose, or environmental storytelling.",
  "The image is sharp, photorealistic, premium, minimal, contemporary, and free of artificial grain, blur, warping, or oversharpening.",
  "There is enough controlled visual space for a separate deterministic typography layer.",
  "There is no typography, pseudo-typography, random glyph, logo, QR code, border, metadata, certification, edition, ownership, or UI layer inside the artwork.",
  "The artwork could credibly become an official alternate I AM NOBODY cover after human review.",
] as const;

export const NOBODY_HARD_REJECTION_RULES = [
  "more than one person",
  "human face, facial feature, hair, or skin visible around the helmet",
  "figure not front-facing",
  "profile or three-quarter pose",
  "sitting, leaning, action pose, or exaggerated gesture",
  "canonical helmet missing, moved, resized, redesigned, rotated, detached, or visually altered",
  "duplicate helmet outline, second visor, exposed head, generated helmet, halo, or seam around the canonical helmet",
  "canonical helmet does not connect naturally to the clothing neckline and shoulders",
  "inconsistent lighting direction or impossible shadows between helmet, collar, shoulders, and body",
  "malformed anatomy, duplicated limb, impossible shoulder, broken hand, extra finger, missing finger, or fused fingers",
  "crop materially closer or farther than the canonical cover",
  "busy or literal environment",
  "more than one prop",
  "readable text, pseudo-text, random letters, numbers, glyphs, logo, watermark, QR code, metadata, border, or UI visible",
  "fantasy, superhero, cyberpunk, gaming, horror, or NFT-collectible styling",
] as const;
